"""Create users table with GitHub fields

Revision ID: 442dd7654cf5
Revises: eeb932a3f249
Create Date: 2025-08-15 17:02:28.161025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442dd7654cf5'
down_revision: Union[str, Sequence[str], None] = 'eeb932a3f249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'active')
    # ### end Alembic commands ###
