"""Create users table with GitHub fields

Revision ID: eeb932a3f249
Revises: 0fbc8ba62ee2
Create Date: 2025-08-15 16:30:33.685184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeb932a3f249'
down_revision: Union[str, Sequence[str], None] = '0fbc8ba62ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('access_token', sa.String(), nullable=True))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_access_token'), 'sessions', ['access_token'], unique=True)
    op.drop_column('sessions', 'session_token')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('sessions', sa.Column('session_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sessions_access_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('sessions', 'access_token')
    # ### end Alembic commands ###
